# Generated by Django 2.0.7 on 2018-07-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pal',
            old_name='fightingClass',
            new_name='generalClass',
        ),
        migrations.AddField(
            model_name='pal',
            name='classDetails',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pal',
            name='profile',
            field=models.CharField(max_length=200),
        ),
    ]
