# Generated by Django 2.0.7 on 2018-07-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0002_auto_20180704_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pal',
            old_name='generalClass',
            new_name='fighterClass',
        ),
    ]
