# Generated by Django 2.0.7 on 2018-07-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0003_auto_20180704_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pal',
            old_name='fighterClass',
            new_name='fightingClass',
        ),
    ]
