# Generated by Django 2.0.7 on 2018-07-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0004_auto_20180704_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pal',
            old_name='fightingClass',
            new_name='characterClass',
        ),
    ]
