# Generated by Django 2.0.7 on 2018-07-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0007_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
