# Generated by Django 2.0.7 on 2019-02-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0009_answer_answer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pal',
            name='marriageable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pal',
            name='maxLevel',
            field=models.IntegerField(default=81),
            preserve_default=False,
        ),
    ]
