# Generated by Django 2.0.7 on 2019-02-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0010_auto_20190215_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pal',
            name='url',
            field=models.CharField(default='uesp.net', max_length=200),
            preserve_default=False,
        ),
    ]
