# Generated by Django 2.0.7 on 2019-02-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pals', '0011_pal_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pal',
            name='classDetails',
        ),
    ]
